ApplicationWithCodeFirst/Models/ApplicationDbContext.cs
using ApplicationWithCodeFirst.Models.Entities;
using Microsoft.EntityFrameworkCore;

namespace ApplicationWithCodeFirst.Models
{
	public class ApplicationDbContext:DbContext
	{

	    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options): base(options)
		{

		}
		public DbSet<Product> products { get; set; }
		public DbSet<Category> categories { get; set; }
	}
}

ApplicationWithCodeFirst/Models/Entities/Category.cs
namespace ApplicationWithCodeFirst.Models.Entities
{
    public class Category
    {
        public int CategoryId { get; set; }
        public string? CategoryName { get; set; }
        public string? Description { get; set; }

        public virtual ICollection<Product> Products { get; set; }

    }
}

ApplicationWithCodeFirst/Models/Entities/Product.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace ApplicationWithCodeFirst.Models.Entities
{
    public class Product
    {
		public int ProductId { get; set; }
		public string? ProductName { get; set; }
		public string? Description { get; set; }

		public decimal Price { get; set; }
		public string? Image { get; set; }

		//public IFormFile File { get; set; } 
		public int CategoryId { get; set; }

		[ForeignKey("CategoryId")]
		public virtual Category Category { get; set; }

	}
}

ApplicationWithCodeFirst/Models/EntitiesVM/CategoryVM.cs
namespace ApplicationWithCodeFirst.Models.EntitiesVM
{
	public class CategoryVM
	{
		public string? CategoryName { get; set; }
		public string? Description { get; set; }
	}
}

ApplicationWithCodeFirst/Models/EntitiesVM/ProductvM.cs
namespace ApplicationWithCodeFirst.Models.EntitiesVM
{
	public class ProductvM
	{
		public string? ProductName { get; set; }
		public string? Description { get; set; }

		public decimal Price { get; set; }
		public string? Image { get; set; }

		public int CategoryId { get; set; }
	}
}

ApplicationWithCodeFirst/Models/ErrorViewModel.cs
namespace ApplicationWithCodeFirst.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

ApplicationWithCodeFirst/Controllers/CategoryController.cs
using ApplicationWithCodeFirst.Application.Services;
using ApplicationWithCodeFirst.Models.Entities;
using Microsoft.AspNetCore.Mvc;

namespace ApplicationWithCodeFirst.Controllers
{
	public class CategoryController : Controller
	{
		private readonly ICategoryServices _categoryService;
		public CategoryController(ICategoryServices categoryServices) 
		{ 
		  _categoryService= categoryServices;	
		}	
        public IActionResult Index()
		{

			return View(_categoryService.GetAllCategories()) ;
		}

		public IActionResult Add()
		{

			return View();
		}

		[HttpPost]
		public IActionResult Add(Category category)
		{

			return View();
		}


		public IActionResult Update()
		{

			return View("Add");
		}

		[HttpPost]
		public IActionResult Update(Category category)
		{

			return View();
		}


		public IActionResult Delete()
		{ 
		
			return View();
		}
	}
}

ApplicationWithCodeFirst/Controllers/HomeController.cs
using ApplicationWithCodeFirst.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ApplicationWithCodeFirst.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

ApplicationWithCodeFirst/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;

namespace ApplicationWithCodeFirst.Controllers
{
	public class ProductController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

ApplicationWithCodeFirst/Views/Category/Index.cshtml
@model IEnumerable<ApplicationWithCodeFirst.Models.Entities.Category> 
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="container mt-3">
        <p>Categoryies</p>
        <table class="table">
            <thead>
                <tr>
                    <th>CategoryName</th>
                    <th>FDescription</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model){
                    <tr>
                        <td>@item.CategoryName</td>
                        <td>@item.Description</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

ApplicationWithCodeFirst/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ApplicationWithCodeFirst/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ApplicationWithCodeFirst</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ApplicationWithCodeFirst.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ApplicationWithCodeFirst</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ApplicationWithCodeFirst - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>